using DatabaseFirstDemo.Data;

Console.WriteLine("=== EF Core DATABASE-FIRST demo (real SQL Server, 192.168.1.52/SchoolTest) ===");
Console.WriteLine();
Console.WriteLine("SchoolTestContext + Models/Student.cs were generated by running:");
Console.WriteLine("  dotnet ef dbcontext scaffold \"Server=192.168.1.52;Database=SchoolTest;...\" \\");
Console.WriteLine("    Microsoft.EntityFrameworkCore.SqlServer -o Models -c SchoolTestContext \\");
Console.WriteLine("    --context-dir Data --table \"Student.Student\" -f");
Console.WriteLine("(read-only schema reflection - see README and the comment at the top of");
Console.WriteLine(" Data/SchoolTestContext.cs). This Program.cs just proves the generated");
Console.WriteLine(" context actually opens a connection and reads real rows back.");
Console.WriteLine();

try
{
    using var db = new SchoolTestContext();

    var count = db.Students.Count();
    Console.WriteLine($"Connected OK. Student.Student currently has {count} row(s).");
    Console.WriteLine();
    Console.WriteLine("First 5 rows (StudentId, FirstName, LastName, SchoolId, CreatedDate):");
    Console.WriteLine("------------------------------------------------------------------------");

    var rows = db.Students
        .OrderBy(s => s.StudentId)
        .Take(5)
        .Select(s => new { s.StudentId, s.FirstName, s.LastName, s.SchoolId, s.CreatedDate })
        .ToList();

    foreach (var s in rows)
    {
        Console.WriteLine($"  [{s.StudentId}] {s.FirstName} {s.LastName}  SchoolId={s.SchoolId}  Created={s.CreatedDate:yyyy-MM-dd}");
    }

    Console.WriteLine();
    Console.WriteLine("Done. This proves the full Database-First pipeline: existing table on a");
    Console.WriteLine("real SQL Server -> dotnet ef dbcontext scaffold -> generated C# classes ->");
    Console.WriteLine("queried back out through those same classes.");
}
catch (Exception ex)
{
    // If this project ever gets built/run somewhere that CANNOT reach
    // 192.168.1.52 (a laptop off the office network, a CI runner, etc.), don't
    // let that look like a broken build - the whole point of this sample is
    // that it compiles and the *shape* of Database-First is correct regardless
    // of live connectivity at any given moment. The scaffold already happened
    // once (see Data/SchoolTestContext.cs / Models/Student.cs) and is
    // committed to source control either way.
    Console.WriteLine("Could not reach 192.168.1.52 / SchoolTest from this machine right now:");
    Console.WriteLine($"  {ex.GetType().Name}: {ex.Message}");
    Console.WriteLine();
    Console.WriteLine("That's a live-connectivity issue, not a code problem - SchoolTestContext");
    Console.WriteLine("and Models/Student.cs were already generated from the real schema (see");
    Console.WriteLine("README) and this project still builds cleanly. Re-run once you're on a");
    Console.WriteLine("network that can reach the SQL Server.");
}
